### ISSUE TITLE
Feature Request: Apply rule for URL fragment AND title match

### ISSUE THREAD

**Issue by bonachea** [furybee/chrome-tab-modifier#186]
I want to apply tab renames to Google Docs matching a certain document title regex.

All URLs in Google docs look like:

`https://docs.google.com/document/d/<long-random-string>`

I write a rule for `URL fragment : contains : https://docs.google.com` and then use the Title Matcher field to enter a regex that captures parts of the original title and backreferences like `@1 @2 @3` in the new title to accomplish the renaming I want.

The *problem* is this rule gets applied to ALL google docs, whereas I only want it applied to ones where the Title Matcher regex match also succeeded/matched.

Can you add a checkbox like "require Title Matcher regex to also match"?

**Comment by bonachea** [comment]
On a related note, with the current version I've deployed a rewriting rule with title captures, which works great for documents matching the pattern. 

Unfortunately there's not a way to hide failed captures  (due to the fact that the fix requested by all of #86 #74 #110 for a means to drop unmatched captures was declined).  As a result, any google docs I open that fail the title match end up rewriting the tab to say "@1 @2 @3" etc, which is highly distracting. If there was a syntax or setting for those empty captures to just become blank space, I could use that as a non-ideal workaround for this issue.

**Comment by quilicicf** [comment]
Hi, 

I've got another use case for this feature request. 

I've got lots of different Slack accounts and want to:

* change their icons to something meaningful (not the Slack icon)
* pin them (they're always open, I need the space in my tab-bar)
* still see when I have things to read

For this, I'd like to create two rules: 

* slack org 1 (unread): 
  * on `app.slack.com/{org1_id}` + title matches `([0-9]+) new item`
  * with `org1 icon` update with notification bubble
* slack org 1: 
  * on `app.slack.com/{org1_id}`
  * with `org1 icon`

**Comment by Ullaakut** [comment]
I have the exact same use case as @quilicicf, for slack workspaces as well. It's actually the whole reason I started looking into this plugin.

Would implementing such a feature be complex? I could take a stab at it, but my JS skills are rusty to say the least.

**Comment by sylouuu** [comment]
Out of scope. See the Focused scope section of the README.

Best
